# Generated by Django 3.2 on 2021-05-13 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0002_auto_20210513_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stockmanagement.category'),
            preserve_default=False,
        ),
    ]
