# Generated by Django 3.2 on 2021-05-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0003_alter_stock_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='export_to_CSV',
        ),
    ]
