# Generated by Django 3.2.3 on 2021-05-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0007_auto_20210516_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('cont_person', models.CharField(max_length=50, verbose_name='Contact Person')),
                ('contact_num', models.IntegerField(verbose_name='Contact Number')),
                ('email', models.CharField(default='', max_length=50)),
                ('company_type', models.CharField(max_length=50, verbose_name='Company Type')),
                ('address', models.CharField(max_length=90, verbose_name='Address Line 1')),
                ('address_2', models.CharField(max_length=90, verbose_name='Address Line 2')),
                ('landmark', models.CharField(max_length=50, verbose_name='Landmark')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('pincode', models.IntegerField(verbose_name='Pincode')),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
