# Generated by Django 3.2.3 on 2021-05-23 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0008_auto_20210523_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='company_type',
        ),
        migrations.RemoveField(
            model_name='customerdetails',
            name='cont_person',
        ),
    ]
