# Generated by Django 3.2.3 on 2021-05-24 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0009_auto_20210523_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, choices=[('Furniture', 'Furniture'), ('IT Equipment', 'IT Equipment'), ('Phone', 'Phone')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Invoice_Details',
            fields=[
                ('Invoice_num', models.AutoField(primary_key=True, serialize=False)),
                ('Invoice_type', models.CharField(blank=True, choices=[('Receipt', 'Receipt'), ('Invoice', 'Invoice')], max_length=50, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('Dispatch_through', models.CharField(max_length=50)),
                ('Due_date', models.DateField(blank=True)),
                ('Payment_note', models.TextField(blank=True, max_length=50)),
                ('Cust_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stockmanagement.customerdetails')),
            ],
        ),
    ]
