# Generated by Django 3.2.3 on 2021-05-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0010_auto_20210524_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_details',
            old_name='Payment_note',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='invoice_details',
            name='Dispatch_through',
        ),
        migrations.AddField(
            model_name='invoice_details',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice_details',
            name='Invoice_num',
            field=models.PositiveIntegerField(),
        ),
    ]
