# Generated by Django 3.2.3 on 2021-05-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0011_auto_20210524_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='invoice_details',
            name='Invoice_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
