# Generated by Django 3.2.3 on 2021-05-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0012_auto_20210524_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_details',
            name='Invoice_num',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
