# Generated by Django 3.2.3 on 2021-05-24 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0013_alter_invoice_details_invoice_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=50)),
                ('Qty', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Discount', models.IntegerField(blank=True, default=0, null=True)),
                ('Cgst', models.IntegerField(blank=True, default=0, null=True)),
                ('Sgst', models.IntegerField(blank=True, default=0, null=True)),
                ('Igst', models.IntegerField(blank=True, default=0, null=True)),
                ('Total', models.FloatField()),
                ('Invoice', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stockmanagement.invoice_details')),
            ],
        ),
    ]
