# Generated by Django 3.2.3 on 2021-05-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0014_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_details',
            name='last_updated',
        ),
    ]
