# Generated by Django 3.2.3 on 2021-05-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0016_auto_20210525_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disc_rs',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
