# Generated by Django 3.2.3 on 2021-06-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0018_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issue_quantity',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='receive_quantity',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='issue_quantity',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='receive_quantity',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        
    ]
