# Generated by Django 3.2.3 on 2021-06-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0019_auto_20210607_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
