# Generated by Django 3.2.3 on 2021-06-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0022_alter_stockhistory_issue_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issue_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
